# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[Σ ](bold purple)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
# success_symbol = "[∳ ](bold purple)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
# success_symbol = "[ⓔ ](bold purple)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
# success_symbol = "[∀x∃y](bold purple)" # The "success_symbol" segment is being set to "➜" with the color "bold green"


# (bold green)
# success_symbol = "[☞ ](bold purple)" # The "success_symbol" segment is being set to "➜" with the color "bold green"


[cmd_duration]
min_time = 200
show_notifications = true
min_time_to_notify = 500_000
format = "time: [$duration](bold yellow)"

[battery]
full_symbol = " "
charging_symbol = "  "
discharging_symbol = "  "

[[battery.display]]
threshold = 10
style = "bold red"


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

